export const ACTION = {
  DATASOURCE: {
    ERROR:     'DATASOURCE_ERROR',
    LOADING:    'DATASOURCE_LOADING',
    SET_NAMES: 'DATASOURCE_SET_NAMES',
    SET_DATA:  'DATASOURCE_SET_DATA',
    SET_RANGE: 'DATASOURCE_SET_RANGE'
  }
};

export const API_URL = '';
